name: CI/CD Pipeline for Node.js App

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  
      - name: Install dependencies
        run: npm install

      - name: Run tests and save results
        run: |
          mkdir -p test-results
          npm test > test-results/test-output.txt 2>&1 || true

      - name: Upload test results artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/test-output.txt

  deploy:
    needs: test
    runs-on: [self-hosted, linux]  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download test results artifact
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: ./artifacts

      - name: Display test results
        run: cat ./artifacts/test-output.txt

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Deploy Application
        run: |


